## Proyecto final BOOTCAMP IRONHACK
###### Estrategias de e-COMERCE

COMPANY = GYMSHARK

### PASO 2. FAKE
- website : https://eu.gymshark.com/

##### Importación de librerias

In [153]:
import pandas as pd
import numpy as np
import re

## LIBRERIAS DE DATOS FAKE
import random
from faker import Faker
import pylab as plt

In [154]:
# Importo el CSV de GYMSHARK_PRODUCTS resultante del WebScrapping

gymshark_products = pd.read_csv('gymshark_products.csv')

gymshark_products.head()

,Title,Rating,Colour,Price,Category
0,Crew Socks 3pk,4.2,White/Light Grey Core Marl/Black,€14,women
1,Everyday Seamless Leggings,3.5,Black,€40,women
2,Sports Bottle,4.0,River Stone Grey/Drift Grey,€16,women
3,Crew Socks 5pk,4.4,White,€20,women
4,Vital Seamless 2.0 Leggings,4.1,Black Marl,€55,women

In [155]:
gymshark_products.shape

(2217, 5)

In [156]:
gymshark_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2217 entries, 0 to 2216
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     2217 non-null   object
 1   Rating    2056 non-null   float64
 2   Colour    2212 non-null   object
 3   Price     2217 non-null   object
 4   Category  2217 non-null   object
dtypes: float64(1), object(4)
memory usage: 86.7+ KB

In [157]:
# Definir una función para extraer los valores numéricos de la columna Price.
def extract_price(value):
    # Buscar todos los números después del símbolo del euro
    numbers = re.findall(r'\d+', value)
    # Convertir los números a enteros y devolver el primero encontrado
    if numbers:
        return int(numbers[0])
    else:
        return None

# Aplicar la función a la columna "Price"
gymshark_products['Price'] = gymshark_products['Price'].apply(extract_price)

In [158]:
# Función para generar códigos de stock aleatorios
def generate_stock_code():
    return ''.join([str(random.randint(0, 9)) for _ in range(5)]) + random.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ')

# Agregar la columna "StockCode" al DataFrame gymshark_products
gymshark_products['StockCode'] = gymshark_products.apply(lambda _: generate_stock_code(), axis=1)

In [159]:
gymshark_products.head()

,Title,Rating,Colour,Price,Category,StockCode
0,Crew Socks 3pk,4.2,White/Light Grey Core Marl/Black,14,women,26076R
1,Everyday Seamless Leggings,3.5,Black,40,women,17356H
2,Sports Bottle,4.0,River Stone Grey/Drift Grey,16,women,37452G
3,Crew Socks 5pk,4.4,White,20,women,08380U
4,Vital Seamless 2.0 Leggings,4.1,Black Marl,55,women,25858X

### Tomando como referencia el DataFrame de gymshark_products, procedo a generar un reporte de ventas de datos ficticios.
##### - Período 01 2023 al 31 12 2023 
#####  - Metodología libreria FAKER de PYTHON.

Esta libreria me permitirá a traves de ciertos parametros aletorios, incluir información para hacer una análisis de estrategia de negocio según las compras realizadas por sus clientes a lo largo del período 2023.

- PASO 1. Añadir columnas referentes a:
    - invoice_no
    - stock_code
    - quantity
    - invoice_date
    - customer_id
    - country
    - size

Según FORBES GYMSHAR vendió un entre 300 y 500 MM de dolares durante el período 2023. Basandonos en esta información gestionamos nuestro DataSet FAKER.

In [262]:
%%time
from tqdm import tqdm
import time

# Generar fechas aleatorias para el año 2023
months = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
days_months = {'01':31, '02':28, '03':31, '04':30, '05':31, '06':30,
               '07':31, '08':31, '09':30, '10':31, '11':30, '12':31}

def pick_day(month):
    day = np.random.randint(1, days_months[month] + 1)
    return str(day)

def pick_weekday():
    weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    return np.random.choice(weekdays)

months_random = []
weekdays_random = []
for _ in range(num_rows_desired):
    month = np.random.choice(months, p=[0.05, 0.08, 0.09, 0.07, 0.11, 0.06, 0.09, 0.07, 0.08, 0.07, 0.11, 0.12])
    day = pick_day(month)
    months_random.append(month + '-' + day + '-2023')
    weekdays_random.append(pick_weekday())

# Lista de tamaños disponibles y sus probabilidades de venta
sizes = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL']
probabilidades_tallas = {
    'XXS': 0.05,
    'XS': 0.15,
    'S': 0.3,
    'M': 0.25,
    'L': 0.15,
    'XL': 0.08,
    'XXL': 0.02
}

# Lista de países europeos
countries = ['USA', 'UK', 'Australia', 'Canada', 'France', 'Germany', 'Ireland', 'Italy', 'Netherlands', 'Portugal', 'Spain']

# Proporciones de ventas por país (ajustado según lo requerido)
proporciones_pais = [0.4, 0.25, 0.15, 0.1, 0.05, 0.02, 0.015, 0.01, 0.007, 0.005, 0.003]
proporciones_pais = np.array(proporciones_pais) / np.sum(proporciones_pais)  # Normalizar las probabilidades

# Proporciones de ventas por categoría (ajustado según lo requerido)
proporciones_categorias = {
    'Women': 0.6,
    'Men': 0.3,
    'Accesorios': 0.1
}

# Probabilidades personalizadas para la generación de IDs de cliente
probabilidades_ids = {
    'new_customer': 0.3,  # Probabilidad de generar un nuevo cliente
    'existing_customer': 0.7  # Probabilidad de utilizar un cliente existente
}

# Lista de IDs de cliente existentes
existing_customer_ids = [fake.random_number(digits=5) for _ in range(num_unique_customers)]

# Distribución de ventas por producto (simulada con distribución exponencial)
ventas_por_producto = np.random.exponential(scale=10, size=len(gymshark_products))

# Generar datos simulados de ventas
data = []

for i in tqdm(range(num_rows_desired)):
    invoice_no = fake.random_number(digits=6)
    
    # Seleccionar un producto aleatorio con probabilidad ponderada
    product_index = np.random.choice(range(len(gymshark_products)), p=ventas_por_producto / np.sum(ventas_por_producto))
    stock_code = gymshark_products.iloc[product_index]['StockCode']
    description = gymshark_products.iloc[product_index]['Title']
    
    # Generar tallas aleatorias ponderadas por las probabilidades definidas
    size = np.random.choice(sizes, p=list(probabilidades_tallas.values()))
    
    # Elegir una cantidad ponderada por las probabilidades definidas
    quantity = np.random.choice(np.arange(1, 9), p=probabilidades_cantidad)
    
    # Elegir país ponderado por las proporciones de ventas
    pais = np.random.choice(countries, p=proporciones_pais)

    # Generar fechas aleatorias
    random_date_str = months_random[i] + ' ' + weekdays_random[i] + ' ' + '{:02d}:{:02d}'.format(np.random.randint(0, 24), np.random.randint(0, 60))
    
    # Aplicar variación de precio por país y por mes
    precio_pais = gymshark_products.iloc[product_index]['Price'] * (1 + variacion_precio_pais.get(pais, 0))
    month = int(months_random[i][:2])
    if month == 11:
        precio_pais *= 0.8  # Reducción del 20% en noviembre
    elif month == 12:
        precio_pais *= 1.1  # Aumento del 10% en diciembre
    
    # Generar ID de cliente
    if np.random.random() < probabilidades_ids['new_customer'] and len(existing_customer_ids) < num_unique_customers:
        customer_id = fake.random_number(digits=5)
        existing_customer_ids.append(customer_id)
    else:
        customer_id = np.random.choice(existing_customer_ids)
        
    # Elegir categoría ponderada por las proporciones de ventas
    categoria = np.random.choice(list(proporciones_categorias.keys()), p=list(proporciones_categorias.values()))
    
    # Asignar rating aleatorio de gymshark_products
    rating = np.random.choice(gymshark_products['Rating'])
    
    colour = np.random.choice(gymshark_products['Colour'])

    data.append([invoice_no, stock_code, description, size, quantity, random_date_str, customer_id, pais, rating, colour, precio_pais, categoria])

# Crear DataFrame de ventas simuladas
columns = ['InvoiceNo', 'StockCode', 'Description', 'Size', 'Quantity', 'InvoiceDate', 'CustomerID', 'Country', 'Rating', 'Colour', 'Price', 'Category']
sales_gymshark23_6 = pd.DataFrame(data, columns=columns)

100%|██████████| 100000/100000 [02:37<00:00, 636.44it/s]

CPU times: total: 1min 20s
Wall time: 2min 45s

In [263]:
sales_gymshark23_6

,InvoiceNo,StockCode,Description,Size,Quantity,InvoiceDate,CustomerID,Country,Rating,Colour,Price,Category
0,282618,76203V,Apex T-Shirt,L,1,11-22-2023 Tuesday 11:30,17849,Australia,4.5,River Stone Grey/Drift Grey,34.04,Men
1,178838,43343R,Pursuit Duffle Bag,M,3,12-25-2023 Tuesday 11:54,90379,USA,4.6,Black/White,91.96,Women
2,317707,11168Y,Everyday Mini Backpack,L,1,03-30-2023 Saturday 09:05,73114,UK,NaN,Dusk Green,31.50,Women
3,998032,21561X,No Show Performance Socks,S,6,02-21-2023 Monday 15:44,21105,USA,5.0,Plum Pink Marl,9.90,Men
4,986803,64146P,GS X Libby Shorts,L,1,03-12-2023 Thursday 09:29,23910,USA,4.2,Camo Brown,44.00,Men
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,895419,75928N,"React 7"" Shorts",S,4,02-23-2023 Sunday 21:28,314,UK,5.0,Slate Lavender,39.90,Women
99996,630510,13084B,Bold Joggers- Black,XS,3,01-9-2023 Tuesday 21:16,47633,UK,4.0,Deep Olive Green,37.80,Women
99997,653024,62129D,Woven Pocket Shorts,S,3,09-8-2023 Friday 07:25,18220,UK,4.4,Black,27.30,Women
99998,177876,21561X,No Show Performance Socks,L,2,03-2-2023 Wednesday 06:23,27167,UK,4.5,Light Grey Marl,9.45,Women
99999,519834,15210V,Woven Pocket Shorts,S,2,06-28-2023 Sunday 19:54,40700,USA,4.3,Black,28.60,Women

In [264]:
sales_gymshark23_6.to_csv('sales_gymshark23_6np.csv', index=False)

#

### BASE DE DATOS DE CLIENTES FAKE

##### Creamos una base de datos de clientes fake

In [92]:
# Obtener valores únicos de las columnas CustomerID y Country
customer_ids_unique = sales_gymshark23_3['CustomerID'].unique()
countries_unique = sales_gymshark23_3['Country'].unique()

# Definir los países disponibles
countries = ['USA', 'UK', 'Australia', 'Canada', 'France', 'Germany', 'Ireland', 'Italy', 'Netherlands', 'Portugal', 'Spain']

# Crear una lista de nombres y géneros aleatorios relacionados
names = [fake.first_name() for _ in range(len(customer_ids_unique))]
last_names = [fake.last_name() for _ in range(len(customer_ids_unique))]

genders = ['Women' if name.lower() in ['Emily', 'Emma', 'Olivia', 'Ava', 'Isabella', 'Sophia', 'Mia', 'Charlotte', 'Amelia', 'Harper',
                                    'Evelyn', 'Abigail', 'Ella', 'Scarlett', 'Grace', 'Chloe', 'Victoria', 'Lily', 'Layla', 'Riley',  
                                    'Zoey', 'Nora', 'Lillian', 'Addison', 'Ellie', 'Hannah', 'Brooklyn', 'Paisley', 'Audrey', 'Savannah',
                                    'Maria', 'Anna', 'Sophia', 'Laura', 'Julia'] 
           
           else 'Men' if name.lower() in ['Paco', 'Juan', 'Carlos', 'Miguel', 'Jose','Liam', 'Noah', 'Oliver', 'Elijah', 'William',
                                          'James', 'Benjamin', 'Lucas', 'Henry', 'Alexander',    'Mason', 'Michael', 'Ethan', 'Daniel',
                                          'Jacob', 'Logan', 'Jackson', 'Levi', 'Sebastian', 'Mateo','Jack', 'Owen', 'Theodore', 'Aiden', 
                                          'Samuel', 'Joseph', 'John', 'David', 'Wyatt', 'Matthew', 'Oliver', 'George', 'Harry', 'Noah', 'Jack',
                                          'Leo', 'Arthur', 'Oscar', 'Muhammad', 'Charlie', 'Henry', 'Thomas', 'William', 'Jacob', 'Alfie',
                                          'Archie', 'Joshua', 'Freddie', 'Theo', 'Isaac']
           
           else 'Others' for name in names]

# Definir los rangos de edades y sus proporciones
age_ranges = ['18-25', '25-35', '36-45', '46-55', '56-60']
age_proportions = [0.2, 0.3, 0.25, 0.15, 0.1]  # Proporciones para cada grupo de edad

# Generar las edades para cada cliente
ages = [random.randint(int(range_.split('-')[0]), int(range_.split('-')[1])) for range_ in random.choices(age_ranges, weights=age_proportions, k=len(customer_ids_unique))]

# Crear DataFrame customer
customer = pd.DataFrame({
    'CustomerID': customer_ids_unique,
    'Name': names,
    'Lastname': last_names,
    'Age': ages,
    'Gender': genders,
    'Country': random.choices(countries, k=len(customer_ids_unique))  # Seleccionar países aleatorios de la lista de países disponibles
})

In [94]:
customer.head()

   CustomerID       Name Lastname  Age  Gender    Country
0       46524  Cassandra    Roach   18  Others    Germany
1       56479    Brandon  Johnson   48  Others    Germany
2       61540   Kimberly   Flores   27  Others     France
3       67582   Samantha  Griffin   18  Others  Australia
4       41971    Crystal  Jackson   32  Others   Portugal

In [95]:
customer.to_csv('customer.csv', index=False)